kind: pipeline
# type: docker
name: default

steps:
- name: greeting
  image: alpine
  volumes:
  - name: cache
    path: /var/git_local
  commands:
  - cat test.txt
  - echo hello > /var/git_local/test.txt
  - echo world >> /var/git_local/test.txt
  - sleep 5

volumes:
- name: cache
  host:
    path: /tmp/cache

trigger:
  branch:
  - staging

# node:
#   env: staging

---
kind: pipeline
# type: docker
name: ecr
steps:
- name: publish
  image: plugins/ecr
  settings:
    access_key:
      from_secret: access_key
    secret_key:
      from_secret: secret_key
    region: ap-northeast-1
    repo: ruby
    registry: 427794181662.dkr.ecr.ap-northeast-1.amazonaws.com
    tags:
    - latest
    - ${DRONE_COMMIT}

trigger:
  branch:
  - staging

# node:
#   env: staging
---

kind: pipeline
type: ssh
name: default-ssh

clone:
  disable: true

server:
  host:
    from_secret: host
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

steps:
- name: ssh
  commands:
  - KUBECONFIG=/home/ec2-user/.kube/config
  - REPO=427794181662.dkr.ecr.ap-northeast-1.amazonaws.com/ruby
  - kubectl --kubeconfig $KUBECONFIG set image deploy ruby ruby=$REPO:${DRONE_COMMIT}

trigger:
  branch:
  - staging

node:
  env: staging

depends_on:
  - ecr