kind: pipeline
# type: docker
name: default

clone:
  disable: true

steps:
- name: check
  image: sinlead/drone-fast-git:0.2.0-rc
  commands:
    # - git fetch origin staging
    # - git diff --exit-code origin/staging...$DRONE_COMMIT_SHA
    - sleep 1000000000

volumes:
- name: cache
  host:
    path: /tmp/cache

trigger:
  branch:
  - staging

# node:
#   env: staging

# ---
# kind: pipeline
# type: docker
# name: ecr
# steps:
# - name: publish
#   image: plugins/ecr
#   settings:
#     access_key:
#       from_secret: access_key
#     secret_key:
#       from_secret: secret_key
#     region: ap-northeast-1
#     repo: ruby
#     registry: 427794181662.dkr.ecr.ap-northeast-1.amazonaws.com
#     tags:
#     - latest
#     - ${DRONE_COMMIT}

# trigger:
#   branch:
#   - staging

# node:
#   env: staging
# ---

# kind: pipeline
# type: ssh
# name: default-ssh

# clone:
#   disable: true

# server:
#   host:
#     from_secret: host
#   user:
#     from_secret: username
#   ssh_key:
#     from_secret: ssh_key

# steps:
# - name: ssh
#   commands:
#   - KUBECONFIG=/home/ec2-user/.kube/config
#   - REPO=427794181662.dkr.ecr.ap-northeast-1.amazonaws.com/ruby
#   - kubectl --kubeconfig $KUBECONFIG set image deploy ruby ruby=$REPO:${DRONE_COMMIT}

# trigger:
#   branch:
#   - staging

# node:
#   env: staging

# depends_on:
#   - ecr