kind: pipeline
type: docker
name: default

# clone:
#   disable: true

steps:
- name: greeting
  image: alpine
  volumes:
  - name: cache
    path: /var/git_local
  commands:
  - cat test.txt
  - echo hello > /var/git_local/test.txt
  - echo world >> /var/git_local/test.txt

volumes:
- name: cache
  host:
    path: /tmp/cache

---
kind: pipeline
type: ssh
name: default-ssh

server:
  host:
    from_secret: host
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

steps:
- name: greeting
  commands:
  - echo 'hello world'