kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  volumes:
  - name: cache
    path: /var/git_local
  commands:
  - cat test.txt
  - echo hello > /var/git_local/test.txt
  - echo world >> /var/git_local/test.txt

volumes:
- name: cache
  host:
    path: /tmp/cache